### ISSUE TITLE
larger chunks?

### ISSUE THREAD

**Issue by topdogmsn** [mr-chibi/claim_protection#1]
how can I make the chunks larger?

**Comment by mr-chibi** [comment]
Will be releasing a patch for that 👍 
Sorry, for the long wait, haven't found a way to add members to claims yet, but releasing this fix will change entire datapack. I **recommend removing all datapack scoreboard data & claims in server before running thoses commands and updating pack!**

/function #protection:uninstall
/datapack disable "file/claim_protection"

Then do the following below:
1. /scoreboard players add username claims 1000
2. /trigger claim
3. /trigger claims_expand

**Comment by mr-chibi** [comment]
Issues is resolved most recent update is release and can be found on PMC:
https://www.planetminecraft.com/data-pack/claim-protection/
