### ISSUE TITLE
Claim inside other Claim possible in 1.18

### ISSUE THREAD

**Issue by acul009** [mr-chibi/claim_protection#2]
Hi,
first of all, thanks for the datapack!
I just tried it and it seems awesome so far.
However, I found an issue on my server. Others can claim inside already existing claims.
The Error message is thrown, but the claim is still created and works.

If I can help to solve the issue , let me know.

**Comment by acul009** [comment]
#3 This seemed to work, but I'm not sure if I damaged anything else with this change

**Comment by mr-chibi** [comment]
Thanks, for the help 👍 
I'm gonna plan on rewriting entire thing since minecraft has new and better entities!
